(()=>{
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const NODES=['N01','N02','N03'];
const NODE_META={N01:{zone:'West Entry',battery:96},N02:{zone:'North Drift',battery:95},N03:{zone:'Center Panel',battery:94}};
const LIMITS={
 tilt:{min:0,max:7,warn:2.5,crit:5,unit:'°',label:'Tilt',sensor:'MPU6050'},
 vibration:{min:0,max:1,warn:.30,crit:.65,unit:' RMS',label:'Vibration',sensor:'MPU6050'},
 displacement:{min:0,max:10,warn:4,crit:7.5,unit:' mm',label:'Relative displacement',sensor:'VL53L0X'},
 risk:{min:0,max:100,warn:36,crit:66,unit:'/100',label:'Mine risk',sensor:'AI fusion'}
};
const SEED=[
 {timestamp:'2026-09-09T10:00:00+05:30',node_id:'N01',tilt:.72,vibration:.10,displacement:1.10,battery:96,source_type:'seed'},
 {timestamp:'2026-09-09T10:00:02+05:30',node_id:'N02',tilt:.80,vibration:.12,displacement:1.20,battery:95,source_type:'seed'},
 {timestamp:'2026-09-09T10:00:04+05:30',node_id:'N03',tilt:.76,vibration:.11,displacement:1.15,battery:94,source_type:'seed'},
 {timestamp:'2026-09-09T10:01:00+05:30',node_id:'N02',tilt:2.55,vibration:.30,displacement:4.20,battery:94,source_type:'seed'},
 {timestamp:'2026-09-09T10:01:02+05:30',node_id:'N03',tilt:2.80,vibration:.34,displacement:4.60,battery:93,source_type:'seed'},
 {timestamp:'2026-09-09T10:02:00+05:30',node_id:'N02',tilt:4.95,vibration:.66,displacement:7.80,battery:92,source_type:'seed'},
 {timestamp:'2026-09-09T10:02:02+05:30',node_id:'N03',tilt:5.40,vibration:.74,displacement:8.70,battery:92,source_type:'seed'}
];
const SCENARIOS={
 normal:{risk:14,scale:.16},warning:{risk:52,scale:.56},critical:{risk:78,scale:.82},subsidence:{risk:91,scale:.97}
};
let activeNode='N02',range='2m',scenario='normal',dataset=[],uploadedRows=null;
function toast(msg){let t=$('#toast');if(!t){t=document.createElement('div');t.id='toast';t.className='toast';document.body.appendChild(t)}t.textContent='NEXGEN · '+msg;t.classList.add('show');clearTimeout(window.__nxv3);window.__nxv3=setTimeout(()=>t.classList.remove('show'),1800)}
function riskForRow(r){const a=Math.min(1,Math.abs(r.tilt)/6),b=Math.min(1,Math.abs(r.vibration)/.9),c=Math.min(1,Math.abs(r.displacement)/10);return Math.round(100*(.28*a+.24*b+.48*c))}
function level(v){return v>=66?'CRITICAL':v>=36?'WARNING':'NORMAL'}
function augmentFromSeed(){let out=[];const start=new Date('2026-09-09T10:00:00+05:30');for(let i=0;i<40;i++){let phase=i<10?.10+i*.006:i<27?.18+(i-10)*.037:.82-(i-27)*.025;NODES.forEach((id,j)=>{const base=SEED[j],f=id==='N01'?.45:id==='N02'?1:.9,s=Math.max(.05,phase)*f;const r={timestamp:new Date(start.getTime()+i*3000+j*700).toISOString(),node_id:id,tilt:+(base.tilt+s*5+Math.sin(i*.43+j)*.06).toFixed(2),vibration:+(base.vibration+s*.68+Math.cos(i*.38+j)*.012).toFixed(2),displacement:+(base.displacement+s*8.3+Math.sin(i*.31+j)*.10).toFixed(2),battery:+(base.battery-i*.03).toFixed(1),source_type:'simulated'};r.risk=riskForRow(r);out.push(r)})});SEED.forEach(r=>{const x={...r};x.risk=riskForRow(x);out.push(x)});return out.sort((a,b)=>new Date(a.timestamp)-new Date(b.timestamp))}
async function loadRepoDataset(){dataset=augmentFromSeed();if(location.protocol!=='file:'){try{const res=await fetch('/assets/prototype_augmented_dataset.csv',{cache:'no-store'});if(res.ok){const text=await res.text(),lines=text.trim().split(/\r?\n/),h=lines.shift().split(',');const parsed=lines.map(line=>{const c=line.split(','),o={};h.forEach((k,i)=>o[k]=c[i]);['tilt','vibration','displacement','battery'].forEach(k=>o[k]=Number(o[k]));o.risk=riskForRow(o);return o}).filter(x=>NODES.includes(x.node_id));if(parsed.length)dataset=parsed}}catch(e){}}renderDatasetFromSource();drawAllFixed();}
function enhanceTelemetry(){const view=$('#view-telemetry');if(!view||$('.v3-telemetry-controls'))return;const controls=document.createElement('div');controls.className='v3-telemetry-controls';controls.innerHTML=`<div class="v3-control-group"><span class="v3-label">NODE</span>${NODES.map(n=>`<button class="v3-pill v3-node ${n===activeNode?'active':''}" data-v3-node="${n}">${n}</button>`).join('')}</div><div class="v3-control-group"><span class="v3-label">WINDOW</span><button class="v3-pill v3-range" data-v3-range="1m">1 MIN</button><button class="v3-pill v3-range active" data-v3-range="2m">2 MIN</button><button class="v3-pill v3-range" data-v3-range="5m">5 MIN</button></div><div class="v3-control-group"><span class="v3-label">LIMITS</span><span style="font-size:7px;color:#596d66">Prototype calibrated thresholds · field calibration required</span></div>`;view.insertBefore(controls,view.firstChild);
 const ribbon=document.createElement('div');ribbon.className='v3-status-ribbon';ribbon.innerHTML='<div class="blue"><small>TILT LIMIT</small><b>2.5° warn · 5.0° critical</b></div><div class="violet"><small>VIBRATION LIMIT</small><b>0.30 warn · 0.65 critical</b></div><div class="amber"><small>DISPLACEMENT LIMIT</small><b>4.0 mm warn · 7.5 mm critical</b></div><div class="green"><small>RISK ENGINE</small><b>36 warn · 66 critical</b></div>';controls.after(ribbon);
 $$('#view-telemetry .chart').forEach((card,i)=>{if(card.querySelector('.v3-chart-meta'))return;const keys=['tilt','vibration','displacement','risk'],m=LIMITS[keys[i]];const meta=document.createElement('div');meta.className='v3-chart-meta';meta.innerHTML=`<span>Y-axis ${m.min}${m.unit} → ${m.max}${m.unit}</span><span class="v3-limit-key"><span><i class="n"></i>Normal</span><span><i class="w"></i>Warning</span><span><i class="c"></i>Critical</span></span>`;card.querySelector('.head')?.after(meta)});
}
function enhanceDataset(){const view=$('#view-dataset .section');if(!view||$('.v3-dataset-source'))return;const source=document.createElement('div');source.className='v3-dataset-source';source.innerHTML='<div class="v3-source-icon">DS</div><div><b>Prototype telemetry dataset loaded</b><p>Uses the repository seed measurements as anchors and a deterministic prototype augmentation for graph continuity. It is demo/training data, not validated mine-field data.</p></div><span>7 SEED ROWS + AUGMENTED SERIES</span>';const top=view.querySelector('.teleTop');if(top)top.after(source);const head=view.querySelector('.head>div:last-child');if(head&&!$('#v3Upload')){const up=document.createElement('button');up.className='btn';up.id='v3Upload';up.textContent='UPLOAD CSV';head.prepend(up);const inp=document.createElement('input');inp.id='v3Csv';inp.type='file';inp.accept='.csv';inp.hidden=true;head.appendChild(inp)}}
function visibleRows(){const src=uploadedRows||dataset;return src.filter(r=>r.node_id===activeNode)}
function windowRows(){const rows=visibleRows();const n=range==='1m'?20:range==='2m'?40:70;return rows.slice(-n)}
function scenarioAdjust(rows,key){const cfg=SCENARIOS[scenario],target=cfg.scale;return rows.map((r,i)=>{let v=Number(r[key]||0),t=i/Math.max(1,rows.length-1);if(scenario==='normal')v*=.45;if(scenario==='warning')v*=.72+.22*t;if(scenario==='critical')v*=.88+.22*t;if(scenario==='subsidence')v*=.92+.34*t;if(key==='risk')v=Math.max(v,SCENARIOS[scenario].risk*(.55+.45*t));return {...r,[key]:v}})}
function drawFixed(canvas,key){if(!canvas)return;const spec=LIMITS[key],raw=windowRows();let rows=raw.map(r=>({...r,risk:r.risk??riskForRow(r)}));rows=scenarioAdjust(rows,key);const rect=canvas.getBoundingClientRect();if(rect.width<20)return;const d=Math.min(window.devicePixelRatio||1,2);canvas.width=rect.width*d;canvas.height=rect.height*d;const c=canvas.getContext('2d'),w=canvas.width,h=canvas.height,pL=42*d,pR=14*d,pT=12*d,pB=28*d,pw=w-pL-pR,ph=h-pT-pB;const y=v=>pT+(spec.max-v)/(spec.max-spec.min)*ph,x=i=>pL+pw*i/Math.max(1,rows.length-1);c.clearRect(0,0,w,h);
 const band=(a,b,color)=>{c.fillStyle=color;c.fillRect(pL,y(b),pw,y(a)-y(b))};band(spec.min,spec.warn,'rgba(22,156,104,.055)');band(spec.warn,spec.crit,'rgba(217,137,18,.065)');band(spec.crit,spec.max,'rgba(217,72,95,.065)');
 c.font=`${7*d}px Segoe UI, sans-serif`;c.textAlign='right';c.textBaseline='middle';for(let i=0;i<=4;i++){const val=spec.min+(spec.max-spec.min)*(4-i)/4,yy=pT+ph*i/4;c.strokeStyle='#dbe4e0';c.lineWidth=d;c.beginPath();c.moveTo(pL,yy);c.lineTo(w-pR,yy);c.stroke();c.fillStyle='#73857f';c.fillText((key==='risk'?Math.round(val):val.toFixed(key==='vibration'?2:1))+spec.unit,pL-6*d,yy)}
 [[spec.warn,'#d98912','WARN'],[spec.crit,'#d9485f','CRIT']].forEach(([v,col,label])=>{c.save();c.setLineDash([4*d,4*d]);c.strokeStyle=col;c.beginPath();c.moveTo(pL,y(v));c.lineTo(w-pR,y(v));c.stroke();c.restore();c.fillStyle=col;c.textAlign='left';c.fillText(label+' '+v+spec.unit,pL+5*d,y(v)-7*d)});
 const grad=c.createLinearGradient(pL,0,w-pR,0);grad.addColorStop(0,key==='tilt'?'#2563eb':key==='vibration'?'#7c3aed':key==='displacement'?'#0891b2':'#d9485f');grad.addColorStop(1,key==='tilt'?'#0891b2':key==='vibration'?'#2563eb':key==='displacement'?'#169c68':'#7c3aed');c.strokeStyle=grad;c.lineWidth=2.3*d;c.beginPath();rows.forEach((r,i)=>{const v=Math.max(spec.min,Math.min(spec.max,Number(r[key]||0))),xx=x(i),yy=y(v);i?c.lineTo(xx,yy):c.moveTo(xx,yy)});c.stroke();
 c.fillStyle='#73857f';c.textAlign='center';c.textBaseline='top';const marks=[0,Math.floor((rows.length-1)/2),rows.length-1];marks.forEach(i=>{if(!rows[i])return;const dt=new Date(rows[i].timestamp);c.fillText(dt.toLocaleTimeString([],{minute:'2-digit',second:'2-digit'}),x(i),h-pB+7*d)});
 canvas.dataset.v3Key=key;canvas.dataset.v3Rows=JSON.stringify(rows.map(r=>({timestamp:r.timestamp,value:r[key]})));
}
function drawAllFixed(){drawFixed($('#cTilt'),'tilt');drawFixed($('#cVib'),'vibration');drawFixed($('#cDisp'),'displacement');drawFixed($('#cRisk'),'risk');updateTelemetryCards();}
function updateTelemetryCards(){let rows=windowRows(),last=rows[rows.length-1]||SEED[1];const mul=scenario==='normal'?.45:scenario==='warning'?.9:scenario==='critical'?1.08:1.22;const t=+(last.tilt*mul).toFixed(2),v=+(last.vibration*mul).toFixed(2),d=+(last.displacement*mul).toFixed(2),r=SCENARIOS[scenario].risk;if($('#tTilt'))$('#tTilt').textContent=t.toFixed(2)+'°';if($('#tVib'))$('#tVib').textContent=v.toFixed(2);if($('#tDisp'))$('#tDisp').textContent=d.toFixed(2)+' mm';if($('#tRisk'))$('#tRisk').textContent=r+' / 100';if($('#tTiltTrend'))$('#tTiltTrend').textContent=scenario==='normal'?'Stable · below warning limit':'Rising · threshold watch active';}
function renderDatasetFromSource(){const tb=$('#dataRows');if(!tb)return;const src=(uploadedRows||dataset).slice(-28).reverse();tb.innerHTML=src.map(r=>{const risk=r.risk??riskForRow(r),lv=level(risk).toLowerCase();return `<tr><td>${new Date(r.timestamp).toLocaleTimeString()}</td><td><b>${r.node_id}</b></td><td>${Number(r.tilt).toFixed(2)}°</td><td>${Number(r.vibration).toFixed(2)}</td><td>${Number(r.displacement).toFixed(2)} mm</td><td>${risk}</td><td><span class="badge ${lv}">${level(risk)}</span></td></tr>`}).join('');const ks=$$('#view-dataset .teleK b');if(ks.length>=4){const all=uploadedRows||dataset;const levels=all.map(r=>level(r.risk??riskForRow(r)));ks[0].textContent=all.length.toLocaleString();ks[1].textContent=levels.filter(x=>x==='NORMAL').length;ks[2].textContent=levels.filter(x=>x==='WARNING').length;ks[3].textContent=levels.filter(x=>x==='CRITICAL').length}}
function parseCsv(text){const lines=text.trim().split(/\r?\n/);if(lines.length<2)throw Error('CSV has no data rows');const h=lines.shift().split(',').map(x=>x.trim());const need=['timestamp','node_id','tilt','vibration','displacement'];if(!need.every(k=>h.includes(k)))throw Error('CSV needs timestamp,node_id,tilt,vibration,displacement');return lines.map(line=>{const c=line.split(','),o={};h.forEach((k,i)=>o[k]=c[i]);['tilt','vibration','displacement','battery'].forEach(k=>o[k]=Number(o[k]||0));o.risk=riskForRow(o);return o}).filter(r=>NODES.includes(r.node_id))}
function exportCsv(){const rows=uploadedRows||dataset,h=['timestamp','node_id','tilt','vibration','displacement','battery','risk'];const text=[h.join(','),...rows.map(r=>h.map(k=>r[k]??'').join(','))].join('\n');const blob=new Blob([text],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='nexgen_prototype_telemetry.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);toast('CSV exported')}
function trainDemo(){const btn=$('#train');if(!btn)return;let wrap=$('.v3-progress-wrap');if(!wrap){wrap=document.createElement('div');wrap.className='v3-progress-wrap';wrap.innerHTML='<small>Preparing prototype feature matrix…</small><div class="v3-progress"><i></i></div>';btn.parentElement.parentElement.after(wrap)}wrap.classList.add('show');const bar=wrap.querySelector('i'),label=wrap.querySelector('small');let p=0;const timer=setInterval(()=>{p+=17;bar.style.width=Math.min(100,p)+'%';if(p>=34)label.textContent='Training Isolation Forest on prototype telemetry…';if(p>=68)label.textContent='Validating anomaly baseline…';if(p>=100){clearInterval(timer);label.textContent='Model ready · prototype training complete';toast('Prototype AI model retrained');setTimeout(()=>wrap.classList.remove('show'),2200)}},220)}
function setScenario(name){scenario=name in SCENARIOS?name:'normal';$$('[data-v2-scenario],.scenario[data-scenario]').forEach(b=>{const n=b.dataset.v2Scenario||b.dataset.scenario;b.classList.toggle('active',n===scenario)});drawAllFixed();toast(scenario.toUpperCase()+' analytics loaded')}
function setView(v){$$('.nav button[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$$('.view').forEach(x=>x.classList.toggle('active',x.id==='view-'+v));const titles={dashboard:['COMMAND CENTER','Mine Command Center'],sensors:['SENSOR NETWORK','Field Sensor Network'],telemetry:['LIVE TELEMETRY','Live Telemetry'],ai:['AI INTELLIGENCE','AI Intelligence'],dataset:['DATASET LAB','Dataset Lab'],alerts:['ALERT CENTER','Alert Center'],system:['SYSTEM HEALTH','System Health']};if(titles[v]){if($('#crumb'))$('#crumb').textContent=titles[v][0];if($('#title'))$('#title').textContent=titles[v][1]}if(v==='telemetry')setTimeout(drawAllFixed,60);if(v==='dataset')renderDatasetFromSource()}
function bindRobustControls(){document.addEventListener('click',e=>{const nav=e.target.closest('.nav button[data-view]');if(nav){e.preventDefault();e.stopImmediatePropagation();setView(nav.dataset.view);return}const scen=e.target.closest('[data-v2-scenario],.scenario[data-scenario]');if(scen){e.preventDefault();e.stopImmediatePropagation();setScenario(scen.dataset.v2Scenario||scen.dataset.scenario);return}const node=e.target.closest('[data-v3-node]');if(node){activeNode=node.dataset.v3Node;$$('[data-v3-node]').forEach(b=>b.classList.toggle('active',b.dataset.v3Node===activeNode));drawAllFixed();toast(activeNode+' selected');return}const rg=e.target.closest('[data-v3-range]');if(rg){range=rg.dataset.v3Range;$$('[data-v3-range]').forEach(b=>b.classList.toggle('active',b.dataset.v3Range===range));drawAllFixed();return}if(e.target.closest('#export')){e.preventDefault();e.stopImmediatePropagation();exportCsv();return}if(e.target.closest('#train')){e.preventDefault();e.stopImmediatePropagation();trainDemo();return}if(e.target.closest('#v3Upload,#v2Upload')){e.preventDefault();e.stopImmediatePropagation();let inp=$('#v3Csv')||$('#v2File');if(inp)inp.click();return}if(e.target.closest('#refresh')){e.preventDefault();e.stopImmediatePropagation();loadRepoDataset();toast('Telemetry refreshed');return}},true);
 document.addEventListener('change',async e=>{if(e.target.matches('#v3Csv,#v2File')){const f=e.target.files?.[0];if(!f)return;try{uploadedRows=parseCsv(await f.text());renderDatasetFromSource();drawAllFixed();toast(uploadedRows.length+' CSV rows loaded')}catch(err){toast(err.message)}}});
}
function tooltip(){if($('.v3-tooltip'))return;const t=document.createElement('div');t.className='v3-tooltip';document.body.appendChild(t);$$('#view-telemetry canvas').forEach(cv=>cv.addEventListener('mousemove',e=>{const rows=JSON.parse(cv.dataset.v3Rows||'[]');if(!rows.length)return;const r=cv.getBoundingClientRect(),idx=Math.max(0,Math.min(rows.length-1,Math.round((e.clientX-r.left)/r.width*(rows.length-1)))),p=rows[idx],key=cv.dataset.v3Key,m=LIMITS[key];t.innerHTML=`<b>${m.label}: ${Number(p.value).toFixed(key==='vibration'?2:1)}${m.unit}</b><small>${activeNode} · ${new Date(p.timestamp).toLocaleTimeString()}</small>`;t.style.left=e.clientX+'px';t.style.top=e.clientY+'px';t.classList.add('show')}));$$('#view-telemetry canvas').forEach(cv=>cv.addEventListener('mouseleave',()=>t.classList.remove('show')))}
function init(){enhanceTelemetry();enhanceDataset();bindRobustControls();tooltip();loadRepoDataset();window.addEventListener('resize',()=>setTimeout(drawAllFixed,80));setTimeout(drawAllFixed,250)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else setTimeout(init,60);
})();
