const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
document.body.innerHTML=`
<div class="app">
<aside class="side">
  <div class="brand"><div class="logo">N</div><div><b>NEXGEN <strong>SENTINEL</strong></b><small>Mine Intelligence Platform</small></div></div>
  <div class="site"><small>ACTIVE SITE</small><b>Underground Mine · Panel A</b><span>3-node prototype deployment</span></div>
  <nav class="nav">
    <button class="active" data-view="dashboard"><i class="ico">01</i><span>Dashboard</span><em>01</em></button>
    <button data-view="sensors"><i class="ico">02</i><span>Sensor Network</span><em>02</em></button>
    <button data-view="telemetry"><i class="ico">03</i><span>Live Telemetry</span><em>03</em></button>
    <button data-view="ai"><i class="ico">04</i><span>AI Intelligence</span><em>04</em></button>
    <button data-view="dataset"><i class="ico">05</i><span>Dataset Lab</span><em>05</em></button>
    <button data-view="alerts"><i class="ico">06</i><span>Alert Center</span><em>06</em></button>
    <button data-view="system"><i class="ico">07</i><span>System Health</span><em>07</em></button>
  </nav>
  <div class="foot"><div class="hline"><i class="dot ok"></i><span>Gateway API</span><b id="sBackend">CHECKING</b></div><div class="hline"><i class="dot ok"></i><span>AI Engine</span><b>ACTIVE</b></div><div class="hline"><i class="dot warn"></i><span>Telegram</span><b>STANDBY</b></div><div class="sih">SIH 2026 · SIH26025</div></div>
</aside>
<main class="work">
<header class="top"><div><div class="crumb"><b>NEXGEN</b> / <span id="crumb">COMMAND CENTER</span></div><h1 id="title">Mine Command Center</h1><div class="sub" id="subtitle">Spatially aware multi-node mine subsidence monitoring and early warning.</div></div><div class="right"><div class="chip live"><small>DATA MODE</small><b id="mode">LIVE / DEMO</b></div><div class="chip"><small>LOCAL TIME</small><b id="clock">--:--:--</b></div><button class="refresh" id="refresh">↻</button></div></header>
<div class="main">
<section class="view active" id="view-dashboard">
  <div class="hero">
    <article class="surface risk"><div class="head"><div><span class="k">MINE HEALTH · REAL-TIME</span><h2>Operational Risk Index</h2></div><span class="badge normal" id="riskBadge">NORMAL</span></div><div class="riskbody"><div class="gauge" id="gauge"><div><small>RISK</small><strong id="risk">14</strong><span>/100</span></div></div><div class="riskcopy"><span class="k">CURRENT ASSESSMENT</span><h3 id="headline">Mine conditions stable</h3><p id="summary"></p><div class="track"><i id="riskBar"></i></div><div class="rmeta"><div><small>DOMINANT NODE</small><b id="domNode">N02</b></div><div><small>AFFECTED ZONE</small><b id="zone">Panel A · Stable</b></div><div><small>AI CONFIDENCE</small><b id="conf">91%</b></div></div></div></div></article>
    <div class="kpis"><article class="surface kpi"><div class="ki">ND</div><div><small>ACTIVE NODES</small><strong>3 / 3</strong><span>Network telemetry online</span></div></article><article class="surface kpi"><div class="ki">AL</div><div><small>ACTIVE ALERTS</small><strong id="alertCount">0</strong><span>Warning + critical</span></div></article><article class="surface kpi"><div class="ki">DB</div><div><small>DATA RECORDS</small><strong id="records">1,284</strong><span>Training-ready stream</span></div></article></div>
  </div>
  <div class="grid2">
    <article class="surface map"><div class="head"><div><span class="k">SPATIAL INTELLIGENCE</span><h2>Mine Panel Digital View</h2></div><span class="badge normal">LIVE MAP</span></div><div class="mine"><div class="tunnel t1"></div><div class="tunnel t2"></div><div class="shaft"></div><div class="cluster" id="cluster"><span>SPATIAL RISK CLUSTER</span></div><button class="node n1 normal"><b>N01</b><small>WEST ENTRY</small><em>12</em></button><button class="node n2 normal"><b>N02</b><small>NORTH DRIFT</small><em>14</em></button><button class="node n3 normal"><b>N03</b><small>CENTER PANEL</small><em>11</em></button></div></article>
    <article class="surface ai"><div class="head"><div><span class="k">AI DECISION SUPPORT</span><h2>Intelligence Brief</h2></div><span class="badge normal">AI ACTIVE</span></div><div class="insight"><small>ASSESSMENT</small><h3 id="aiTitle"></h3><p id="aiText"></p></div><div class="bars"><div class="barrow"><span>ML Anomaly</span><b id="b1v"></b><div class="bar"><i id="b1"></i></div></div><div class="barrow"><span>Temporal Trend</span><b id="b2v"></b><div class="bar"><i id="b2"></i></div></div><div class="barrow"><span>Spatial Correlation</span><b id="b3v"></b><div class="bar"><i id="b3"></i></div></div></div><div class="recommend"><small>RECOMMENDATION</small><b id="recommend"></b></div></article>
  </div>
</section>
<section class="view" id="view-sensors"><article class="surface section"><div class="head"><div><span class="k">FIELD HARDWARE</span><h2>Sensor Network · 3 Active Nodes</h2></div><span class="badge normal">3 / 3 ONLINE</span></div><div class="cards3" id="sensorCards"></div></article></section>
<section class="view" id="view-telemetry"><div class="teleTop"><article class="surface teleK"><small>TILT · MPU6050</small><b id="tTilt"></b><span id="tTiltTrend"></span></article><article class="surface teleK"><small>VIBRATION RMS · MPU6050</small><b id="tVib"></b><span>Continuous inertial monitoring</span></article><article class="surface teleK"><small>DISPLACEMENT · VL53L0X</small><b id="tDisp"></b><span>Relative to calibrated baseline</span></article><article class="surface teleK"><small>MINE RISK</small><b id="tRisk"></b><span>Fused intelligence score</span></article></div><div class="charts"><article class="surface chart"><div class="head"><div><span class="k">TELEMETRY</span><h2>Tilt vs Time</h2></div><span class="badge normal">MPU6050</span></div><canvas id="cTilt"></canvas></article><article class="surface chart"><div class="head"><div><span class="k">TELEMETRY</span><h2>Vibration RMS vs Time</h2></div><span class="badge normal">MPU6050</span></div><canvas id="cVib"></canvas></article><article class="surface chart"><div class="head"><div><span class="k">TELEMETRY</span><h2>Relative Displacement vs Time</h2></div><span class="badge normal">VL53L0X</span></div><canvas id="cDisp"></canvas></article><article class="surface chart"><div class="head"><div><span class="k">FUSED OUTPUT</span><h2>Mine Risk vs Time</h2></div><span class="badge normal">AI FUSION</span></div><canvas id="cRisk"></canvas></article></div></section>
<section class="view" id="view-ai"><div class="aiLayout"><article class="surface riskBreak"><span class="k">EXPLAINABLE INTELLIGENCE</span><h2>Mine Risk Decomposition</h2><div class="bigAI" id="bigAi">14</div><div class="bars"><div class="barrow"><span>Sensor Severity · 40%</span><b id="a1v"></b><div class="bar"><i id="a1"></i></div></div><div class="barrow"><span>Temporal Trend · 25%</span><b id="a2v"></b><div class="bar"><i id="a2"></i></div></div><div class="barrow"><span>ML Anomaly · 20%</span><b id="a3v"></b><div class="bar"><i id="a3"></i></div></div><div class="barrow"><span>Spatial Correlation · 15%</span><b id="a4v"></b><div class="bar"><i id="a4"></i></div></div></div></article><article class="surface fusion"><span class="k">AI ENGINE</span><h2>Decision Support</h2><div class="fusiongrid"><div><small>MODEL</small><b>Isolation Forest</b></div><div><small>STATUS</small><b>ACTIVE</b></div><div><small>TRAINING SAMPLES</small><b>1,120</b></div><div><small>ACTIVE FEATURES</small><b>3 + Spatial</b></div></div><div class="insight"><small>HUMAN-READABLE EXPLANATION</small><h3 id="expTitle"></h3><p id="expText"></p></div><div class="recommend"><small>OPERATOR ACTION</small><b id="expAction"></b></div></article></div></section>
<section class="view" id="view-dataset"><article class="surface section"><div class="head"><div><span class="k">DATA OPERATIONS</span><h2>Dataset Lab</h2></div><div><button class="btn primary" id="train">RETRAIN MODEL</button> <button class="btn" id="export">EXPORT CSV</button></div></div><div class="teleTop" style="margin-top:13px"><article class="surface teleK"><small>TOTAL RECORDS</small><b>1,284</b><span>Prototype telemetry</span></article><article class="surface teleK"><small>NORMAL</small><b>1,096</b><span>Stable samples</span></article><article class="surface teleK"><small>WARNING</small><b>142</b><span>Elevated samples</span></article><article class="surface teleK"><small>CRITICAL</small><b>46</b><span>High-severity samples</span></article></div><div class="tablewrap"><table class="table"><thead><tr><th>TIME</th><th>NODE</th><th>TILT</th><th>VIBRATION</th><th>DISPLACEMENT</th><th>RISK</th><th>STATE</th></tr></thead><tbody id="dataRows"></tbody></table></div></article></section>
<section class="view" id="view-alerts"><div class="alerts"><article class="surface timeline"><div class="head"><div><span class="k">EARLY WARNING OPERATIONS</span><h2>Alert Timeline</h2></div><span class="badge warning">AUTOMATED</span></div><div id="alertList"></div></article><article class="surface phone"><div class="ph"><h3>NexGen Alerts</h3><div class="msg"><small>BOT · NOW</small><b id="phoneTitle"></b><p id="phoneMsg"></p><small>Telegram early-warning preview</small></div></div></article></div></section>
<section class="view" id="view-system"><div class="sysgrid"><article class="surface systile"><div class="si">API</div><div><small>BACKEND</small><b id="sysApi">CHECKING</b><span>FastAPI service</span></div><i class="dot ok"></i></article><article class="surface systile"><div class="si">WS</div><div><small>LIVE STREAM</small><b>READY</b><span>WebSocket telemetry</span></div><i class="dot ok"></i></article><article class="surface systile"><div class="si">DB</div><div><small>DATA STORE</small><b>CONNECTED</b><span>SQLite prototype DB</span></div><i class="dot ok"></i></article><article class="surface systile"><div class="si">AI</div><div><small>AI MODEL</small><b>ACTIVE</b><span>Isolation Forest</span></div><i class="dot ok"></i></article><article class="surface systile"><div class="si">TG</div><div><small>TELEGRAM</small><b>STANDBY</b><span>Alert delivery</span></div><i class="dot warn"></i></article><article class="surface systile"><div class="si">GW</div><div><small>GATEWAY</small><b>READY</b><span>Wi-Fi / LoRa architecture</span></div><i class="dot ok"></i></article></div><article class="surface demo"><div class="head"><div><span class="k">SIH PRESENTATION MODE</span><h2>One-Click Jury Demo Controls</h2></div><span class="badge normal">SAFE DEMO</span></div><div class="scenarios"><button class="scenario normal" data-scenario="normal"><b>NORMAL OPERATION</b><small>All nodes stable</small></button><button class="scenario warning" data-scenario="warning"><b>WARNING STATE</b><small>Elevated deformation trend</small></button><button class="scenario critical" data-scenario="critical"><b>CRITICAL STATE</b><small>High-severity signature</small></button><button class="scenario subsidence" data-scenario="subsidence"><b>PROGRESSIVE SUBSIDENCE</b><small>Multi-node spatial cascade</small></button></div></article></section>
</div></main></div><div class="toast" id="toast">NEXGEN · Dashboard updated</div>`;

const pages={dashboard:['COMMAND CENTER','Mine Command Center','Spatially aware multi-node mine subsidence monitoring and early warning.'],sensors:['SENSOR NETWORK','Field Sensor Network','Node-level health and measurements from MPU6050 and VL53L0X.'],telemetry:['LIVE TELEMETRY','Live Telemetry','Continuous tilt, vibration, displacement and fused mine-risk trends.'],ai:['AI INTELLIGENCE','AI Intelligence','Explainable anomaly, trend and spatial-correlation analysis.'],dataset:['DATASET LAB','Dataset Lab','Prototype telemetry records and training-ready sensor data.'],alerts:['ALERT CENTER','Alert Center','Risk transitions and operator early-warning delivery.'],system:['SYSTEM HEALTH','System Health','Prototype readiness, service health and jury demo controls.']};
const scenarios={normal:{risk:14,levels:['normal','normal','normal'],vals:[[.72,.11,1.1],[.88,.13,1.3],[.79,.10,1.0]],an:18,tr:14,sp:12,title:'Mine conditions stable',sum:'All three prototype nodes are inside the normal operating envelope. Continuous trend and spatial correlation monitoring remain active.',ai:'Stable multi-node signature',ait:'No dominant anomaly or correlated deformation pattern detected across adjacent nodes.',rec:'Continue standard monitoring.'},warning:{risk:52,levels:['normal','warning','warning'],vals:[[1.4,.18,2.1],[3.1,.39,4.8],[2.7,.34,4.1]],an:58,tr:66,sp:53,title:'Elevated movement pattern detected',sum:'N02 and N03 show increasing movement above baseline. Increase monitoring and perform physical verification.',ai:'Multi-sensor warning signature',ait:'Tilt and relative displacement are rising across two adjacent nodes with moderate spatial agreement.',rec:'Increase monitoring frequency and inspect North Drift.'},critical:{risk:78,levels:['warning','critical','warning'],vals:[[2.9,.33,4.0],[5.3,.74,8.5],[3.4,.47,5.9]],an:82,tr:76,sp:68,title:'Critical deformation pattern detected',sum:'N02 shows a high-severity sensor signature with supporting movement on adjacent nodes. Immediate inspection is recommended.',ai:'High-risk anomaly detected',ait:'Rapid displacement increase and abnormal vibration are concentrated at N02, with supporting adjacent-node evidence.',rec:'Restrict access to affected panel and inspect immediately.'},subsidence:{risk:91,levels:['warning','critical','critical'],vals:[[3.6,.45,5.4],[6.1,.86,9.7],[5.7,.78,8.9]],an:94,tr:92,sp:91,title:'Progressive subsidence pattern detected',sum:'Adjacent N02 and N03 exhibit strongly correlated deformation. Multi-node spatial and temporal evidence indicates a progressive event.',ai:'Spatial correlation detected',ait:'Two adjacent nodes show synchronized displacement growth, vibration increase and high anomaly scores — a stronger event signature than any single sensor.',rec:'CRITICAL: isolate Panel A and initiate immediate physical inspection.'}};
let state='normal',backend=false;
function toast(t){$('#toast').textContent='NEXGEN · '+t;$('#toast').classList.add('show');clearTimeout(window.__t);window.__t=setTimeout(()=>$('#toast').classList.remove('show'),2000)}
function statusClass(el,c){el.classList.remove('normal','warning','critical');el.classList.add(c)}
$$('.nav button').forEach(b=>b.addEventListener('click',()=>{$$('.nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(v=>v.classList.remove('active'));$('#view-'+b.dataset.view).classList.add('active');const p=pages[b.dataset.view];$('#crumb').textContent=p[0];$('#title').textContent=p[1];$('#subtitle').textContent=p[2];if(b.dataset.view==='telemetry')requestAnimationFrame(drawAll)}));
setInterval(()=>$('#clock').textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'}),1000);
function apply(name){state=name;const s=scenarios[name],lev=s.risk>=66?'critical':s.risk>=36?'warning':'normal',clr=s.risk>=66?'var(--red)':s.risk>=36?'var(--amber)':'var(--green)';$('#risk').textContent=s.risk;$('#riskBar').style.width=s.risk+'%';$('#riskBar').style.background=clr;$('#gauge').style.background=`conic-gradient(${clr} 0deg ${s.risk*3.6}deg,#e9efeb ${s.risk*3.6}deg 360deg)`;statusClass($('#riskBadge'),lev);$('#riskBadge').textContent=lev.toUpperCase();$('#headline').textContent=s.title;$('#summary').textContent=s.sum;$('#alertCount').textContent=name==='normal'?0:name==='warning'?2:name==='critical'?3:4;$('#zone').textContent=name==='normal'?'Panel A · Stable':'Panel A · North Drift';$('#conf').textContent=(name==='normal'?91:name==='warning'?86:name==='critical'?93:97)+'%';$('#aiTitle').textContent=s.ai;$('#aiText').textContent=s.ait;$('#recommend').textContent=s.rec;[['b1','b1v',s.an],['b2','b2v',s.tr],['b3','b3v',s.sp]].forEach(([a,v,n])=>{$('#'+a).style.width=n+'%';$('#'+v).textContent=n+'%'});$('#cluster').classList.toggle('on',name==='critical'||name==='subsidence');$$('.node').forEach((n,i)=>{statusClass(n,s.levels[i]);n.querySelector('em').textContent=Math.round([s.risk*.65,s.risk,s.risk*.82][i])});renderSensors();renderAI();renderAlerts();updateTele();renderDataset();drawAll()}
function renderSensors(){const s=scenarios[state],zones=['West Entry','North Drift','Center Panel'];$('#sensorCards').innerHTML=['N01','N02','N03'].map((id,i)=>{const v=s.vals[i],l=s.levels[i],r=Math.round([s.risk*.65,s.risk,s.risk*.82][i]);return `<article class="surface nodecard"><div class="nodecardtop"><div><span class="k">FIELD NODE</span><h3>${id}</h3><p>${zones[i]}</p></div><span class="badge ${l}">${l.toUpperCase()}</span></div><div class="score ${l}">${r}</div><span class="k">NODE RISK / 100</span><div class="sens"><div><span>MPU6050 · TILT</span><b>${v[0].toFixed(2)}°</b><small>Inertial angle</small></div><div><span>MPU6050 · VIBRATION</span><b>${v[1].toFixed(2)}</b><small>RMS index</small></div><div><span>VL53L0X · DISPLACEMENT</span><b>${v[2].toFixed(2)} mm</b><small>Relative baseline</small></div><div><span>BATTERY</span><b>${[94,89,92][i]}%</b><small>Node power</small></div></div></article>`}).join('')}
function renderAI(){const s=scenarios[state];$('#bigAi').textContent=s.risk;[['a1','a1v',Math.round(s.risk*.9)],['a2','a2v',s.tr],['a3','a3v',s.an],['a4','a4v',s.sp]].forEach(([a,v,n])=>{$('#'+a).style.width=Math.min(100,n)+'%';$('#'+v).textContent=Math.min(100,n)+'%'});$('#expTitle').textContent=s.ai;$('#expText').textContent=s.ait;$('#expAction').textContent=s.rec}
function renderAlerts(){const s=scenarios[state];const items=state==='normal'?[]:state==='warning'?[['warning','N02 · Warning','Displacement trend exceeded current baseline.'],['warning','N03 · Warning','Adjacent-node movement supports elevated state.']]:state==='critical'?[['critical','N02 · Critical','High-severity displacement and vibration anomaly.'],['warning','N03 · Warning','Supporting spatial evidence detected.'],['warning','Panel A · Escalated','Operator inspection recommended.']]:[['critical','Spatial Cluster · Critical','N02 and N03 show strongly correlated movement.'],['critical','N02 · Critical','Rapid displacement increase detected.'],['critical','N03 · Critical','Synchronized deformation trend detected.'],['warning','Panel A · Restricted','Immediate physical inspection recommended.']];$('#alertList').innerHTML=items.length?items.map(x=>`<div class="alert ${x[0]}"><div class="aico">!</div><div><b>${x[1]}</b><p>${x[2]}</p></div><time>NOW</time></div>`).join(''):'<div class="insight"><small>CURRENT STATUS</small><h3>No active warning</h3><p>All nodes remain within normal operating envelope.</p></div>';$('#phoneTitle').textContent=state==='normal'?'SYSTEM READY':state==='warning'?'WARNING · PANEL A':'CRITICAL MINE ALERT';$('#phoneMsg').textContent=state==='normal'?'No active mine subsidence warning. Monitoring Panel A continuously.':s.rec}
function updateTele(){const s=scenarios[state],v=s.vals[1];$('#tTilt').textContent=v[0].toFixed(2)+'°';$('#tVib').textContent=v[1].toFixed(2);$('#tDisp').textContent=v[2].toFixed(2)+' mm';$('#tRisk').textContent=s.risk+' / 100';$('#tTiltTrend').textContent=state==='normal'?'Stable trend':'Rising trend'}
function series(base,amp,n=42,rise=0){return Array.from({length:n},(_,i)=>base+(Math.sin(i*.45)+Math.sin(i*.13)*.5)*amp+(i/(n-1))*rise)}
function draw(canvas,data,color='#0d7f78'){if(!canvas)return;const r=canvas.getBoundingClientRect();if(r.width<20)return;const dpr=Math.min(devicePixelRatio||1,2);canvas.width=r.width*dpr;canvas.height=r.height*dpr;const c=canvas.getContext('2d'),w=canvas.width,h=canvas.height,p=24*dpr,min=Math.min(...data),max=Math.max(...data);c.clearRect(0,0,w,h);c.strokeStyle='#e0e7e2';c.lineWidth=dpr;for(let i=0;i<5;i++){const y=p+(h-2*p)*i/4;c.beginPath();c.moveTo(p,y);c.lineTo(w-p,y);c.stroke()}c.strokeStyle=color;c.lineWidth=2*dpr;c.beginPath();data.forEach((v,i)=>{const x=p+(w-2*p)*i/(data.length-1),y=p+(max-v)/(max-min||1)*(h-2*p);i?c.lineTo(x,y):c.moveTo(x,y)});c.stroke()}
function drawAll(){const s=scenarios[state],rise=state==='normal'?0:state==='warning'?2:state==='critical'?4:6;draw($('#cTilt'),series(s.vals[1][0]*.7,.12,42,rise*.24));draw($('#cVib'),series(s.vals[1][1]*.7,.025,42,rise*.045),'#d89b24');draw($('#cDisp'),series(s.vals[1][2]*.55,.18,42,rise*.72),'#0d7f78');draw($('#cRisk'),series(Math.max(5,s.risk*.58),2.3,42,rise*4.4),s.risk>=66?'#d84b55':'#0d7f78')}
function renderDataset(){const s=scenarios[state];$('#dataRows').innerHTML=Array.from({length:18},(_,i)=>{const id=['N01','N02','N03'][i%3],v=s.vals[i%3],l=s.levels[i%3],risk=Math.round([s.risk*.65,s.risk,s.risk*.82][i%3]);return `<tr><td>${new Date(Date.now()-i*22000).toLocaleTimeString()}</td><td><b>${id}</b></td><td>${(v[0]+Math.sin(i)*.08).toFixed(2)}°</td><td>${(v[1]+Math.cos(i)*.01).toFixed(2)}</td><td>${(v[2]+Math.sin(i*.6)*.15).toFixed(2)} mm</td><td>${risk}</td><td><span class="badge ${l}">${l.toUpperCase()}</span></td></tr>`}).join('')}
async function tryBackend(){try{const r=await fetch('/api/health',{cache:'no-store'});if(!r.ok)throw new Error();backend=true;$('#mode').textContent='LIVE BACKEND';$('#sBackend').textContent='ONLINE';$('#sysApi').textContent='ONLINE'}catch{backend=false;$('#mode').textContent='STANDALONE DEMO';$('#sBackend').textContent='DEMO';$('#sysApi').textContent='DEMO MODE'}}
$$('.scenario').forEach(b=>b.onclick=async()=>{const n=b.dataset.scenario;if(backend){try{await fetch('/api/simulate/'+n,{method:'POST'})}catch{}}apply(n);toast(n.toUpperCase()+' scenario loaded')});$('#refresh').onclick=()=>{tryBackend();toast('status refreshed')};$('#train').onclick=async()=>{if(backend){try{await fetch('/api/model/train',{method:'POST'});toast('AI model retrained')}catch{toast('training unavailable')}}else toast('demo model refreshed')};$('#export').onclick=()=>{if(backend)location.href='/api/dataset/export.csv';else toast('demo CSV export ready')};window.addEventListener('resize',drawAll);apply('normal');tryBackend();setInterval(renderDataset,12000);